// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBjaaRUDF0_Eb5IAI48GofKseif0OYdoY',
    appId: '1:711157074667:web:3612212a123c004a9d0cae',
    messagingSenderId: '711157074667',
    projectId: 'fir-activity-a2bc2',
    authDomain: 'fir-activity-a2bc2.firebaseapp.com',
    storageBucket: 'fir-activity-a2bc2.firebasestorage.app',
    measurementId: 'G-HZHT653N3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdNQq7F4pfCT5jsl_P6Y7MqVXADD5WxbI',
    appId: '1:711157074667:android:a44d7002786f4d209d0cae',
    messagingSenderId: '711157074667',
    projectId: 'fir-activity-a2bc2',
    storageBucket: 'fir-activity-a2bc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXGiHnYg0-NR1BJE2z7IubYY7k4-iSNP8',
    appId: '1:711157074667:ios:fc056ee951f7f9ec9d0cae',
    messagingSenderId: '711157074667',
    projectId: 'fir-activity-a2bc2',
    storageBucket: 'fir-activity-a2bc2.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXGiHnYg0-NR1BJE2z7IubYY7k4-iSNP8',
    appId: '1:711157074667:ios:fc056ee951f7f9ec9d0cae',
    messagingSenderId: '711157074667',
    projectId: 'fir-activity-a2bc2',
    storageBucket: 'fir-activity-a2bc2.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBjaaRUDF0_Eb5IAI48GofKseif0OYdoY',
    appId: '1:711157074667:web:255328ea83eaa2139d0cae',
    messagingSenderId: '711157074667',
    projectId: 'fir-activity-a2bc2',
    authDomain: 'fir-activity-a2bc2.firebaseapp.com',
    storageBucket: 'fir-activity-a2bc2.firebasestorage.app',
    measurementId: 'G-25ZH849F23',
  );
}
